"""add_asset_model_and_media_linking

Revision ID: 1a8bf9e73960
Revises: 20251218_ai_quota_onboarding
Create Date: 2025-12-18 11:46:53.511758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8bf9e73960'
down_revision: Union[str, None] = '20251218_ai_quota_onboarding'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'flashcard_decks' not in tables:
        op.create_table('flashcard_decks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('subject', sa.String(length=50), nullable=False),
        sa.Column('difficulty', sa.String(length=20), nullable=False),
        sa.Column('card_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_flashcard_decks_id'), 'flashcard_decks', ['id'], unique=False)
        op.create_index(op.f('ix_flashcard_decks_subject'), 'flashcard_decks', ['subject'], unique=False)

    if 'waitlist_leads' not in tables:
        op.create_table('waitlist_leads',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('school_name', sa.String(), nullable=True),
        sa.Column('education_level', sa.String(), nullable=True),
        sa.Column('location', sa.String(), nullable=True),
        sa.Column('device_type', sa.String(), nullable=True),
        sa.Column('referral_source', sa.String(), nullable=True),
        sa.Column('is_converted', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_waitlist_leads_id'), 'waitlist_leads', ['id'], unique=False)
        op.create_index(op.f('ix_waitlist_leads_phone_number'), 'waitlist_leads', ['phone_number'], unique=True)

    if 'assets' not in tables:
        op.create_table('assets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.Column('asset_type', sa.String(length=50), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('ai_metadata', sa.JSON(), nullable=True),
        sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)

    if 'otps' not in tables:
        op.create_table('otps',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=4), nullable=False),
        sa.Column('purpose', sa.String(length=20), nullable=False),
        sa.Column('is_used', sa.Boolean(), nullable=True),
        sa.Column('attempts', sa.Integer(), nullable=True),
        sa.Column('max_attempts', sa.Integer(), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
        op.create_index(op.f('ix_otps_user_id'), 'otps', ['user_id'], unique=False)

    if 'flashcards' not in tables:
        op.create_table('flashcards',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('deck_id', sa.Integer(), nullable=False),
        sa.Column('front', sa.Text(), nullable=False),
        sa.Column('back', sa.Text(), nullable=False),
        sa.Column('image_url', sa.String(length=500), nullable=True),
        sa.Column('asset_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
        sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_flashcards_deck_id'), 'flashcards', ['deck_id'], unique=False)
        op.create_index(op.f('ix_flashcards_id'), 'flashcards', ['id'], unique=False)

    if 'flashcard_reviews' not in tables:
        op.create_table('flashcard_reviews',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('card_id', sa.Integer(), nullable=False),
        sa.Column('ease_factor', sa.Float(), nullable=True),
        sa.Column('interval', sa.Integer(), nullable=True),
        sa.Column('repetitions', sa.Integer(), nullable=True),
        sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['card_id'], ['flashcards.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_flashcard_next_review', 'flashcard_reviews', ['user_id', 'next_review_date'], unique=False)
        op.create_index('idx_flashcard_review_updated', 'flashcard_reviews', ['updated_at'], unique=False)
        op.create_index(op.f('ix_flashcard_reviews_card_id'), 'flashcard_reviews', ['card_id'], unique=False)
        op.create_index(op.f('ix_flashcard_reviews_id'), 'flashcard_reviews', ['id'], unique=False)
        op.create_index(op.f('ix_flashcard_reviews_user_id'), 'flashcard_reviews', ['user_id'], unique=False)

    if 'question_reports' not in tables:
        op.create_table('question_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('reason', sa.Enum('WRONG_ANSWER', 'TYPO', 'UNCLEAR_QUESTION', 'MISSING_DIAGRAM', 'OUTDATED_CONTENT', 'OTHER', name='reportreason'), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('admin_notes', sa.Text(), nullable=True),
        sa.Column('reviewed_by', sa.Integer(), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
        sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_question_reports_id'), 'question_reports', ['id'], unique=False)
        op.create_index(op.f('ix_question_reports_question_id'), 'question_reports', ['question_id'], unique=False)
        op.create_index(op.f('ix_question_reports_user_id'), 'question_reports', ['user_id'], unique=False)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        existing_cols = [c['name'] for c in inspector.get_columns('assignments')]
        if 'subject_filter' not in existing_cols:
            batch_op.add_column(sa.Column('subject_filter', sa.String(length=50), nullable=True))
        if 'topic_filter' not in existing_cols:
            batch_op.add_column(sa.Column('topic_filter', sa.String(length=100), nullable=True))
        if 'difficulty_filter' not in existing_cols:
            batch_op.add_column(sa.Column('difficulty_filter', sa.String(length=20), nullable=True))
        if 'question_count' not in existing_cols:
            batch_op.add_column(sa.Column('question_count', sa.Integer(), nullable=True))
        # batch_op.alter_column('assignment_type',
        #         existing_type=sa.VARCHAR(length=20),
        #         nullable=True,
        #         existing_server_default=sa.text("'quiz'"))
        # batch_op.alter_column('max_points',
        #         existing_type=sa.INTEGER(),
        #         nullable=True,
        #         existing_server_default=sa.text("'100'"))
        # batch_op.alter_column('is_ai_generated',
        #         existing_type=sa.INTEGER(),
        #         nullable=True,
        #         existing_server_default=sa.text("'0'"))
        # batch_op.alter_column('status',
        #         existing_type=sa.VARCHAR(length=20),
        #         nullable=True,
        #         existing_server_default=sa.text("'draft'"))
        # batch_op.alter_column('created_at',
        #         existing_type=sa.DATETIME(),
        #         nullable=True,
        #         existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        # batch_op.alter_column('updated_at',
        #         existing_type=sa.DATETIME(),
        #         nullable=True,
        #         existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        # batch_op.drop_column('subject')
        # batch_op.drop_column('topic')
        # batch_op.drop_column('difficulty')

    with op.batch_alter_table('attempts', schema=None) as batch_op:
        existing_cols = [c['name'] for c in inspector.get_columns('attempts')]
        if 'skipped' not in existing_cols:
            batch_op.add_column(sa.Column('skipped', sa.Boolean(), nullable=True))
        if 'srs_interval' not in existing_cols:
            batch_op.add_column(sa.Column('srs_interval', sa.Integer(), nullable=True))
        if 'srs_ease_factor' not in existing_cols:
            batch_op.add_column(sa.Column('srs_ease_factor', sa.Float(), nullable=True))
        if 'srs_repetitions' not in existing_cols:
            batch_op.add_column(sa.Column('srs_repetitions', sa.Integer(), nullable=True))
        if 'next_review_date' not in existing_cols:
            batch_op.add_column(sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=True))
        if 'created_at' not in existing_cols:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        if 'updated_at' not in existing_cols:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        if 'deleted_at' not in existing_cols:
            batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        if 'device_id' not in existing_cols:
            batch_op.add_column(sa.Column('device_id', sa.String(), nullable=True))
        if 'synced_at' not in existing_cols:
            batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))

    existing_indexes = [idx['name'] for idx in inspector.get_indexes('attempts')]
    if 'idx_next_review' not in existing_indexes:
        op.create_index('idx_next_review', 'attempts', ['user_id', 'next_review_date'], unique=False)
    if 'idx_progress_updated_at' not in existing_indexes:
        op.create_index('idx_progress_updated_at', 'attempts', ['updated_at'], unique=False)
    if 'idx_user_date' not in existing_indexes:
        op.create_index('idx_user_date', 'attempts', ['user_id', 'attempted_at'], unique=False)
    if 'idx_user_question' not in existing_indexes:
        op.create_index('idx_user_question', 'attempts', ['user_id', 'question_id'], unique=False)
    if 'ix_attempts_id' not in existing_indexes:
        op.create_index(op.f('ix_attempts_id'), 'attempts', ['id'], unique=False)
    if 'ix_attempts_question_id' not in existing_indexes:
        op.create_index(op.f('ix_attempts_question_id'), 'attempts', ['question_id'], unique=False)
    if 'ix_attempts_user_id' not in existing_indexes:
        op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)

    with op.batch_alter_table('classroom_materials', schema=None) as batch_op:
        existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('classroom_materials')]
        if 'fk_classroom_materials_asset_id' not in existing_fks:
            batch_op.create_foreign_key('fk_classroom_materials_asset_id', 'assets', ['asset_id'], ['id'])

    existing_indexes = [idx['name'] for idx in inspector.get_indexes('classroom_materials')]
    if 'ix_classroom_materials_classroom_id' not in existing_indexes:
        op.create_index(op.f('ix_classroom_materials_classroom_id'), 'classroom_materials', ['classroom_id'], unique=False)
    if 'ix_classroom_materials_id' not in existing_indexes:
        op.create_index(op.f('ix_classroom_materials_id'), 'classroom_materials', ['id'], unique=False)
    if 'ix_classroom_materials_uploaded_by_id' not in existing_indexes:
        op.create_index(op.f('ix_classroom_materials_uploaded_by_id'), 'classroom_materials', ['uploaded_by_id'], unique=False)
    
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('classroom_posts')]
    if 'ix_classroom_posts_author_id' not in existing_indexes:
        op.create_index(op.f('ix_classroom_posts_author_id'), 'classroom_posts', ['author_id'], unique=False)
    if 'ix_classroom_posts_classroom_id' not in existing_indexes:
        op.create_index(op.f('ix_classroom_posts_classroom_id'), 'classroom_posts', ['classroom_id'], unique=False)
    if 'ix_classroom_posts_id' not in existing_indexes:
        op.create_index(op.f('ix_classroom_posts_id'), 'classroom_posts', ['id'], unique=False)
    
    with op.batch_alter_table('questions', schema=None) as batch_op:
        existing_cols = [c['name'] for c in inspector.get_columns('questions')]
        if 'content' not in existing_cols:
            batch_op.add_column(sa.Column('content', sa.Text(), nullable=False, server_default=''))
        if 'options_json' not in existing_cols:
            batch_op.add_column(sa.Column('options_json', sa.Text(), nullable=False, server_default='[]'))
        if 'correct_index' not in existing_cols:
            batch_op.add_column(sa.Column('correct_index', sa.Integer(), nullable=False, server_default='0'))
        if 'explanation' not in existing_cols:
            batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))
        if 'exam_year' not in existing_cols:
            batch_op.add_column(sa.Column('exam_year', sa.String(), nullable=True))
        if 'asset_id' not in existing_cols:
            batch_op.add_column(sa.Column('asset_id', sa.Integer(), nullable=True))
        if 'updated_at' not in existing_cols:
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        if 'deleted_at' not in existing_cols:
            batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        
        existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('questions')]
        if 'fk_questions_asset_id' not in existing_fks:
            batch_op.create_foreign_key('fk_questions_asset_id', 'assets', ['asset_id'], ['id'])

    existing_indexes = [idx['name'] for idx in inspector.get_indexes('questions')]
    if 'idx_questions_updated_at' not in existing_indexes:
        op.create_index('idx_questions_updated_at', 'questions', ['updated_at'], unique=False)
    if 'ix_questions_id' not in existing_indexes:
        op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    if 'ix_questions_subject' not in existing_indexes:
        op.create_index(op.f('ix_questions_subject'), 'questions', ['subject'], unique=False)
    if 'ix_questions_topic' not in existing_indexes:
        op.create_index(op.f('ix_questions_topic'), 'questions', ['topic'], unique=False)
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        pass

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        pass

    existing_indexes = [idx['name'] for idx in inspector.get_indexes('submissions')]
    if 'ix_submissions_assignment_id' not in existing_indexes:
        op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    if 'ix_submissions_id' not in existing_indexes:
        op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    if 'ix_submissions_student_id' not in existing_indexes:
        op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    
    with op.batch_alter_table('teacher_messages', schema=None) as batch_op:
        pass

    with op.batch_alter_table('users', schema=None) as batch_op:
        existing_cols = [c['name'] for c in inspector.get_columns('users')]
        if 'phone_number' not in existing_cols:
            batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))
        if 'is_verified' not in existing_cols:
            batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        if 'deleted_at' not in existing_cols:
            batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        if 'last_login' not in existing_cols:
            batch_op.add_column(sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))

    existing_indexes = [idx['name'] for idx in inspector.get_indexes('users')]
    if 'ix_users_email' not in existing_indexes:
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    if 'ix_users_id' not in existing_indexes:
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    if 'ix_users_phone_number' not in existing_indexes:
        op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    if 'ix_users_username' not in existing_indexes:
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superuser', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('study_streak',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('has_app_installed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('last_login')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('teacher_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teacher_messages_classroom_id', type_='foreignkey')
        batch_op.drop_constraint('fk_teacher_messages_teacher_id', type_='foreignkey')
        batch_op.drop_constraint('fk_teacher_messages_student_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_teacher_messages_classroom_id', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_teacher_messages_student_id', 'users', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_teacher_messages_teacher_id', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('sent_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_read',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               nullable=False)

    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('is_graded',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_profiles_teacher_id', type_='foreignkey')
        batch_op.drop_constraint('fk_student_profiles_student_id', type_='foreignkey')
        batch_op.drop_constraint('fk_student_profiles_classroom_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_student_profiles_teacher_id', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_student_profiles_student_id', 'users', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_student_profiles_classroom_id', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('uq_classroom_student', ['classroom_id', 'student_id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('contact_frequency',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=False))
        batch_op.drop_constraint('fk_questions_asset_id', type_='foreignkey')
        batch_op.alter_column('difficulty',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('topic',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', name='subject'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('asset_id')
        batch_op.drop_column('exam_year')
        batch_op.drop_column('explanation')
        batch_op.drop_column('correct_index')
        batch_op.drop_column('options_json')
        batch_op.drop_column('content')

    op.drop_index(op.f('ix_questions_topic'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index('idx_questions_updated_at', table_name='questions')
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'true'"))

    with op.batch_alter_table('classroom_students', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    op.drop_index(op.f('ix_classroom_posts_id'), table_name='classroom_posts')
    op.drop_index(op.f('ix_classroom_posts_classroom_id'), table_name='classroom_posts')
    op.drop_index(op.f('ix_classroom_posts_author_id'), table_name='classroom_posts')
    
    with op.batch_alter_table('classroom_materials', schema=None) as batch_op:
        batch_op.drop_constraint('fk_classroom_materials_asset_id', type_='foreignkey')
        batch_op.alter_column('asset_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    op.drop_index(op.f('ix_classroom_materials_uploaded_by_id'), table_name='classroom_materials')
    op.drop_index(op.f('ix_classroom_materials_id'), table_name='classroom_materials')
    op.drop_index(op.f('ix_classroom_materials_classroom_id'), table_name='classroom_materials')
    
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_question_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_id'), table_name='attempts')
    op.drop_index('idx_user_question', table_name='attempts')
    op.drop_index('idx_user_date', table_name='attempts')
    op.drop_index('idx_progress_updated_at', table_name='attempts')
    op.drop_index('idx_next_review', table_name='attempts')
    
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.alter_column('selected_option',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('synced_at')
        batch_op.drop_column('device_id')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('next_review_date')
        batch_op.drop_column('srs_repetitions')
        batch_op.drop_column('srs_ease_factor')
        batch_op.drop_column('srs_interval')
        batch_op.drop_column('skipped')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'"))
        batch_op.alter_column('is_ai_generated',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('max_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'100'"))
        batch_op.alter_column('assignment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'quiz'"))
        batch_op.drop_column('question_count')
        batch_op.drop_column('difficulty_filter')
        batch_op.drop_column('topic_filter')
        batch_op.drop_column('subject_filter')

    op.drop_index(op.f('ix_question_reports_user_id'), table_name='question_reports')
    op.drop_index(op.f('ix_question_reports_question_id'), table_name='question_reports')
    op.drop_index(op.f('ix_question_reports_id'), table_name='question_reports')
    op.drop_table('question_reports')
    op.drop_index(op.f('ix_flashcard_reviews_user_id'), table_name='flashcard_reviews')
    op.drop_index(op.f('ix_flashcard_reviews_id'), table_name='flashcard_reviews')
    op.drop_index(op.f('ix_flashcard_reviews_card_id'), table_name='flashcard_reviews')
    op.drop_index('idx_flashcard_review_updated', table_name='flashcard_reviews')
    op.drop_index('idx_flashcard_next_review', table_name='flashcard_reviews')
    op.drop_table('flashcard_reviews')
    op.drop_index(op.f('ix_flashcards_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_deck_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_otps_user_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_waitlist_leads_phone_number'), table_name='waitlist_leads')
    op.drop_index(op.f('ix_waitlist_leads_id'), table_name='waitlist_leads')
    op.drop_table('waitlist_leads')
    op.drop_index(op.f('ix_flashcard_decks_subject'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_id'), table_name='flashcard_decks')
    op.drop_table('flashcard_decks')
    # ### end Alembic commands ###
