"""strict_enums_for_robustness

Revision ID: d0d79fcca71f
Revises: 1a8bf9e73960
Create Date: 2025-12-18 16:08:38.139022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d79fcca71f'
down_revision: Union[str, None] = '1a8bf9e73960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('subject_filter', existing_type=sa.VARCHAR(length=50), type_=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', 'AGRICULTURAL_SCIENCE', 'COMMERCE', 'LITERATURE_IN_ENGLISH', name='subject'), postgresql_using='subject_filter::subject',
               existing_nullable=True)
        batch_op.alter_column('topic_filter', existing_type=sa.VARCHAR(length=100), type_=sa.Enum('ALGEBRA', 'GEOMETRY', 'TRIGONOMETRY', 'STATISTICS', 'PROBABILITY', 'CALCULUS', 'NUMBER_BASES', 'SETS', 'LOGARITHMS', 'GRAMMAR', 'COMPREHENSION', 'VOCABULARY', 'ORAL_ENGLISH', 'WRITING', 'MECHANICS', 'THERMAL_PHYSICS', 'WAVES', 'ELECTRICITY', 'MAGNETISM', 'ATOMIC_PHYSICS', 'OPTICS', 'ATOMIC_STRUCTURE', 'CHEMICAL_BONDING', 'STOICHIOMETRY', 'STATES_OF_MATTER', 'PERIODIC_TABLE', 'ORGANIC_CHEMISTRY', 'ELECTROCHEMISTRY', 'CELL_BIOLOGY', 'GENETICS', 'ECOLOGY', 'PHYSIOLOGY', 'EVOLUTION', 'CLASSIFICATION', 'GENERAL', 'OTHER', name='topic'), postgresql_using='topic_filter::topic',
               existing_nullable=True)
        batch_op.alter_column('difficulty_filter', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), postgresql_using='difficulty_filter::difficultylevel',
               existing_nullable=True)
        batch_op.alter_column('assignment_type', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('QUIZ', 'MANUAL', 'ESSAY', 'PRACTICE', name='assignmenttype'), postgresql_using='assignment_type::assignmenttype',
               nullable=True,
               existing_server_default=sa.text("'quiz'"))
        batch_op.alter_column('max_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'100'"))
        batch_op.alter_column('is_ai_generated',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('status', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', 'COMPLETED', name='assignmentstatus'), postgresql_using='status::assignmentstatus',
               nullable=True,
               existing_server_default=sa.text("'draft'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('topic')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('subject')

    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.alter_column('selected_option',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('classroom_posts', schema=None) as batch_op:
        batch_op.alter_column('post_type', existing_type=sa.VARCHAR(length=30), type_=sa.Enum('ANNOUNCEMENT', 'DISCUSSION', 'ASSIGNMENT_ALERT', 'COMMENT', 'RESOURCE', name='posttype'), postgresql_using='post_type::posttype',
               existing_nullable=True)

    with op.batch_alter_table('classroom_students', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('subject', existing_type=sa.VARCHAR(length=50), type_=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', 'AGRICULTURAL_SCIENCE', 'COMMERCE', 'LITERATURE_IN_ENGLISH', name='subject'), postgresql_using='subject::subject',
               existing_nullable=True)
        batch_op.alter_column('grade_level', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3', 'UNIVERSITY', 'OTHER', name='gradelevel'), postgresql_using='grade_level::gradelevel',
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'true'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('flashcard_decks', schema=None) as batch_op:
        batch_op.alter_column('subject', existing_type=sa.VARCHAR(length=50), type_=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', 'AGRICULTURAL_SCIENCE', 'COMMERCE', 'LITERATURE_IN_ENGLISH', name='subject'), postgresql_using='subject::subject',
               existing_nullable=False)
        batch_op.alter_column('difficulty', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), postgresql_using='difficulty::difficultylevel',
               existing_nullable=False)

    with op.batch_alter_table('question_reports', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('PENDING', 'REVIEWED', 'FIXED', 'DISMISSED', name='reportstatus'), postgresql_using='status::reportstatus',
               existing_nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('subject', existing_type=sa.VARCHAR(length=100), type_=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', 'AGRICULTURAL_SCIENCE', 'COMMERCE', 'LITERATURE_IN_ENGLISH', name='subject'), postgresql_using='subject::subject',
               existing_nullable=False)
        batch_op.alter_column('topic', existing_type=sa.VARCHAR(length=100), type_=sa.Enum('ALGEBRA', 'GEOMETRY', 'TRIGONOMETRY', 'STATISTICS', 'PROBABILITY', 'CALCULUS', 'NUMBER_BASES', 'SETS', 'LOGARITHMS', 'GRAMMAR', 'COMPREHENSION', 'VOCABULARY', 'ORAL_ENGLISH', 'WRITING', 'MECHANICS', 'THERMAL_PHYSICS', 'WAVES', 'ELECTRICITY', 'MAGNETISM', 'ATOMIC_PHYSICS', 'OPTICS', 'ATOMIC_STRUCTURE', 'CHEMICAL_BONDING', 'STOICHIOMETRY', 'STATES_OF_MATTER', 'PERIODIC_TABLE', 'ORGANIC_CHEMISTRY', 'ELECTROCHEMISTRY', 'CELL_BIOLOGY', 'GENETICS', 'ECOLOGY', 'PHYSIOLOGY', 'EVOLUTION', 'CLASSIFICATION', 'GENERAL', 'OTHER', name='topic'), postgresql_using='topic::topic',
               nullable=False)
        batch_op.alter_column('difficulty', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), postgresql_using='difficulty::difficultylevel',
               existing_nullable=True)
        batch_op.drop_column('text')

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.alter_column('contact_frequency',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint(batch_op.f('uq_classroom_student'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_student_profiles_student_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_student_profiles_teacher_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_student_profiles_classroom_id_classrooms'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_student_profiles_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_student_profiles_student_id_users'), 'users', ['student_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_student_profiles_teacher_id_users'), 'users', ['teacher_id'], ['id'])

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('is_graded',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('teacher_messages', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('sent_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint(batch_op.f('fk_teacher_messages_student_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_teacher_messages_classroom_id_classrooms'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_teacher_messages_teacher_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_teacher_messages_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_teacher_messages_student_id_users'), 'users', ['student_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_teacher_messages_teacher_id_users'), 'users', ['teacher_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('has_app_installed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
        batch_op.alter_column('study_streak',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.drop_column('is_superuser')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superuser', sa.BOOLEAN(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.alter_column('study_streak',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('has_app_installed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('teacher_messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_teacher_messages_teacher_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_teacher_messages_student_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_teacher_messages_classroom_id_classrooms'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_teacher_messages_teacher_id_users'), 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_teacher_messages_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_teacher_messages_student_id_users'), 'users', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('sent_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_read',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('is_graded',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_profiles_teacher_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_student_profiles_student_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_student_profiles_classroom_id_classrooms'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_student_profiles_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_student_profiles_teacher_id_users'), 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_student_profiles_student_id_users'), 'users', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('uq_classroom_student'), ['classroom_id', 'student_id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('contact_frequency',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=False))
        batch_op.alter_column('difficulty',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('topic',
               existing_type=sa.Enum('ALGEBRA', 'GEOMETRY', 'TRIGONOMETRY', 'STATISTICS', 'PROBABILITY', 'CALCULUS', 'NUMBER_BASES', 'SETS', 'LOGARITHMS', 'GRAMMAR', 'COMPREHENSION', 'VOCABULARY', 'ORAL_ENGLISH', 'WRITING', 'MECHANICS', 'THERMAL_PHYSICS', 'WAVES', 'ELECTRICITY', 'MAGNETISM', 'ATOMIC_PHYSICS', 'OPTICS', 'ATOMIC_STRUCTURE', 'CHEMICAL_BONDING', 'STOICHIOMETRY', 'STATES_OF_MATTER', 'PERIODIC_TABLE', 'ORGANIC_CHEMISTRY', 'ELECTROCHEMISTRY', 'CELL_BIOLOGY', 'GENETICS', 'ECOLOGY', 'PHYSIOLOGY', 'EVOLUTION', 'CLASSIFICATION', 'GENERAL', 'OTHER', name='topic'),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', 'AGRICULTURAL_SCIENCE', 'COMMERCE', 'LITERATURE_IN_ENGLISH', name='subject'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('question_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'REVIEWED', 'FIXED', 'DISMISSED', name='reportstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('flashcard_decks', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', 'AGRICULTURAL_SCIENCE', 'COMMERCE', 'LITERATURE_IN_ENGLISH', name='subject'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'true'"))
        batch_op.alter_column('grade_level',
               existing_type=sa.Enum('JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3', 'UNIVERSITY', 'OTHER', name='gradelevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', 'AGRICULTURAL_SCIENCE', 'COMMERCE', 'LITERATURE_IN_ENGLISH', name='subject'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('classroom_students', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('classroom_posts', schema=None) as batch_op:
        batch_op.alter_column('post_type',
               existing_type=sa.Enum('ANNOUNCEMENT', 'DISCUSSION', 'ASSIGNMENT_ALERT', 'COMMENT', 'RESOURCE', name='posttype'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.alter_column('selected_option',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', 'COMPLETED', name='assignmentstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'"))
        batch_op.alter_column('is_ai_generated',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('max_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'100'"))
        batch_op.alter_column('assignment_type',
               existing_type=sa.Enum('QUIZ', 'MANUAL', 'ESSAY', 'PRACTICE', name='assignmenttype'),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'quiz'"))
        batch_op.alter_column('difficulty_filter',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('topic_filter',
               existing_type=sa.Enum('ALGEBRA', 'GEOMETRY', 'TRIGONOMETRY', 'STATISTICS', 'PROBABILITY', 'CALCULUS', 'NUMBER_BASES', 'SETS', 'LOGARITHMS', 'GRAMMAR', 'COMPREHENSION', 'VOCABULARY', 'ORAL_ENGLISH', 'WRITING', 'MECHANICS', 'THERMAL_PHYSICS', 'WAVES', 'ELECTRICITY', 'MAGNETISM', 'ATOMIC_PHYSICS', 'OPTICS', 'ATOMIC_STRUCTURE', 'CHEMICAL_BONDING', 'STOICHIOMETRY', 'STATES_OF_MATTER', 'PERIODIC_TABLE', 'ORGANIC_CHEMISTRY', 'ELECTROCHEMISTRY', 'CELL_BIOLOGY', 'GENETICS', 'ECOLOGY', 'PHYSIOLOGY', 'EVOLUTION', 'CLASSIFICATION', 'GENERAL', 'OTHER', name='topic'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('subject_filter',
               existing_type=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', 'AGRICULTURAL_SCIENCE', 'COMMERCE', 'LITERATURE_IN_ENGLISH', name='subject'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
