"""strict_enums_for_robustness

Revision ID: d0d79fcca71f
Revises: 1a8bf9e73960
Create Date: 2025-12-18 16:08:38.139022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d79fcca71f'
down_revision: Union[str, None] = '1a8bf9e73960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum types for PostgreSQL
    if op.get_bind().dialect.name == 'postgresql':
        # Rename existing types to avoid conflicts with new Title Case definitions
        for type_name in ['subject', 'topic', 'difficultylevel', 'gradelevel', 'assignmenttype', 'assignmentstatus', 'posttype', 'reportstatus', 'reportreason']:
            op.execute(f"DO $$ BEGIN ALTER TYPE {type_name} RENAME TO {type_name}_old; EXCEPTION WHEN undefined_object THEN null; END $$;")
        
        # Create new types with correct casing
        op.execute("CREATE TYPE subject AS ENUM ('Mathematics', 'English Language', 'Physics', 'Chemistry', 'Biology', 'Economics', 'Geography', 'Government', 'Civic Education', 'Financial Accounting', 'Agricultural Science', 'Commerce', 'Literature in English', 'Data Science');")
        op.execute("""
            CREATE TYPE topic AS ENUM (
                'Algebra',
                'Geometry', 
                'Trigonometry',
                'Statistics',
                'Probability',
                'Calculus',
                'Number Bases',
                'Sets',
                'Logarithms',
                'Fractions',
                'Decimals',
                'Ratios',
                'Percentages',
                'Indices',
                'Surds',
                'Grammar',
                'Comprehension',
                'Vocabulary',
                'Oral English',
                'Writing',
                'Mechanics',
                'Thermal Physics',
                'Waves',
                'Electricity',
                'Magnetism',
                'Atomic Physics',
                'Optics',
                'Atomic Structure',
                'Chemical Bonding',
                'Stoichiometry',
                'States of Matter',
                'Periodic Table',
                'Organic Chemistry',
                'Electrochemistry',
                'Cell Biology',
                'Genetics',
                'Ecology',
                'Physiology',
                'Evolution',
                'Classification',
                'General',
                'Other'
            );
        """)
        op.execute("CREATE TYPE difficultylevel AS ENUM ('easy', 'medium', 'hard');")
        op.execute("CREATE TYPE assignmenttype AS ENUM ('quiz', 'manual', 'essay', 'practice');")
        op.execute("CREATE TYPE assignmentstatus AS ENUM ('draft', 'published', 'archived', 'completed');")
        op.execute("CREATE TYPE posttype AS ENUM ('announcement', 'discussion', 'assignment_alert', 'comment', 'resource');")
        op.execute("CREATE TYPE reportstatus AS ENUM ('pending', 'reviewed', 'fixed', 'dismissed');")
        op.execute("CREATE TYPE gradelevel AS ENUM ('JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3', 'Grade 10', 'Grade 11', 'Grade 12', 'University', 'Other');")
        op.execute("CREATE TYPE reportreason AS ENUM ('Wrong Answer', 'Typo', 'Unclear Question', 'Missing Diagram', 'Outdated Content', 'Other');")

        # Convert columns to VARCHAR temporarily to allow any string value during normalization
        for table, col in [('assignments', 'subject_filter'), ('classrooms', 'subject'), ('flashcard_decks', 'subject'), ('questions', 'subject')]:
            op.execute(f"ALTER TABLE {table} ALTER COLUMN {col} TYPE VARCHAR(100)")
        for table, col in [('assignments', 'difficulty_filter'), ('flashcard_decks', 'difficulty'), ('questions', 'difficulty')]:
            op.execute(f"ALTER TABLE {table} ALTER COLUMN {col} TYPE VARCHAR(20)")
        for table, col in [('assignments', 'topic_filter'), ('questions', 'topic')]:
            op.execute(f"ALTER TABLE {table} ALTER COLUMN {col} TYPE VARCHAR(100)")
        op.execute("ALTER TABLE classrooms ALTER COLUMN grade_level TYPE VARCHAR(20)")
        op.execute("ALTER TABLE question_reports ALTER COLUMN reason TYPE VARCHAR(50)")
        op.execute("ALTER TABLE question_reports ALTER COLUMN status TYPE VARCHAR(20)")

        # Normalize data in tables before casting
        # Subject normalization
        for table, col in [('assignments', 'subject_filter'), ('classrooms', 'subject'), ('flashcard_decks', 'subject'), ('questions', 'subject')]:
            op.execute(f"UPDATE {table} SET {col} = INITCAP({col}::text) WHERE {col} IS NOT NULL")
            op.execute(f"UPDATE {table} SET {col} = 'English Language' WHERE {col}::text = 'English'")
            op.execute(f"UPDATE {table} SET {col} = 'Civic Education' WHERE {col}::text = 'Civic_education'")
            op.execute(f"UPDATE {table} SET {col} = 'Financial Accounting' WHERE {col}::text = 'Financial_accounting'")
            op.execute(f"UPDATE {table} SET {col} = 'Agricultural Science' WHERE {col}::text = 'Agricultural_science'")
            op.execute(f"UPDATE {table} SET {col} = 'Literature in English' WHERE {col}::text = 'Literature_in_english'")
            # Map any remaining unknown values to 'Other'
            valid_subjects = ('Mathematics', 'English Language', 'Physics', 'Chemistry', 'Biology', 'Economics', 'Geography', 'Government', 'Civic Education', 'Financial Accounting', 'Agricultural Science', 'Commerce', 'Literature in English', 'Data Science')
            op.execute(f"UPDATE {table} SET {col} = 'Other' WHERE {col}::text NOT IN {valid_subjects}")
            op.execute(f"UPDATE {table} SET {col} = 'Data Science' WHERE {col}::text = 'Data_science'")

        # Difficulty normalization
        for table, col in [('assignments', 'difficulty_filter'), ('flashcard_decks', 'difficulty'), ('questions', 'difficulty')]:
            op.execute(f"UPDATE {table} SET {col} = LOWER({col}::text) WHERE {col} IS NOT NULL")

        # Topic normalization
        for table, col in [('assignments', 'topic_filter'), ('questions', 'topic')]:
            op.execute(f"UPDATE {table} SET {col} = INITCAP({col}::text) WHERE {col} IS NOT NULL")
            op.execute(f"UPDATE {table} SET {col} = 'Number Bases' WHERE {col}::text = 'Number_bases'")
            op.execute(f"UPDATE {table} SET {col} = 'Oral English' WHERE {col}::text = 'Oral_english'")
            op.execute(f"UPDATE {table} SET {col} = 'Thermal Physics' WHERE {col}::text = 'Thermal_physics'")
            op.execute(f"UPDATE {table} SET {col} = 'Atomic Physics' WHERE {col}::text = 'Atomic_physics'")
            op.execute(f"UPDATE {table} SET {col} = 'Atomic Structure' WHERE {col}::text = 'Atomic_structure'")
            op.execute(f"UPDATE {table} SET {col} = 'Chemical Bonding' WHERE {col}::text = 'Chemical_bonding'")
            op.execute(f"UPDATE {table} SET {col} = 'States of Matter' WHERE {col}::text = 'States_of_matter'")
            op.execute(f"UPDATE {table} SET {col} = 'Periodic Table' WHERE {col}::text = 'Periodic_table'")
            op.execute(f"UPDATE {table} SET {col} = 'Organic Chemistry' WHERE {col}::text = 'Organic_chemistry'")
            op.execute(f"UPDATE {table} SET {col} = 'Cell Biology' WHERE {col}::text = 'Cell_biology'")
            # Map any remaining unknown values to 'Other'
            valid_topics = ('Algebra', 'Geometry', 'Trigonometry', 'Statistics', 'Probability', 'Calculus', 'Number Bases', 'Sets', 'Logarithms', 'Fractions', 'Decimals', 'Ratios', 'Percentages', 'Indices', 'Surds', 'Grammar', 'Comprehension', 'Vocabulary', 'Oral English', 'Writing', 'Mechanics', 'Thermal Physics', 'Waves', 'Electricity', 'Magnetism', 'Atomic Physics', 'Optics', 'Atomic Structure', 'Chemical Bonding', 'Stoichiometry', 'States of Matter', 'Periodic Table', 'Organic Chemistry', 'Electrochemistry', 'Cell Biology', 'Genetics', 'Ecology', 'Physiology', 'Evolution', 'Classification', 'General', 'Other')
            op.execute(f"UPDATE {table} SET {col} = 'Other' WHERE {col}::text NOT IN {valid_topics}")

        # Grade Level normalization
        op.execute("""
            UPDATE classrooms SET grade_level = CASE 
                WHEN UPPER(grade_level::text) IN ('JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3') THEN UPPER(grade_level::text)
                WHEN grade_level::text ILIKE 'grade%10%' THEN 'Grade 10'
                WHEN grade_level::text ILIKE 'grade%11%' THEN 'Grade 11'
                WHEN grade_level::text ILIKE 'grade%12%' THEN 'Grade 12'
                WHEN UPPER(grade_level::text) = 'UNIVERSITY' THEN 'University'
                ELSE INITCAP(grade_level::text)
            END WHERE grade_level IS NOT NULL
        """)

        # Report Reason normalization
        op.execute("""
            UPDATE question_reports SET reason = CASE 
                WHEN reason::text = 'WRONG_ANSWER' THEN 'Wrong Answer'
                WHEN reason::text = 'TYPO' THEN 'Typo'
                WHEN reason::text = 'UNCLEAR_QUESTION' THEN 'Unclear Question'
                WHEN reason::text = 'MISSING_DIAGRAM' THEN 'Missing Diagram'
                WHEN reason::text = 'OUTDATED_CONTENT' THEN 'Outdated Content'
                ELSE 'Other'
            END WHERE reason IS NOT NULL
        """)

        # Drop defaults that cause casting issues in PostgreSQL
        op.execute("ALTER TABLE assignments ALTER COLUMN assignment_type DROP DEFAULT;")
        op.execute("ALTER TABLE assignments ALTER COLUMN status DROP DEFAULT;")

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('subject_filter', existing_type=sa.VARCHAR(length=100), type_=sa.Enum('Mathematics', 'English Language', 'Physics', 'Chemistry', 'Biology', 'Economics', 'Geography', 'Government', 'Civic Education', 'Financial Accounting', 'Agricultural Science', 'Commerce', 'Literature in English', 'Data Science', name='subject'), postgresql_using='subject_filter::subject',
               existing_nullable=True)
        batch_op.alter_column('topic_filter', existing_type=sa.VARCHAR(length=100), type_=sa.Enum('Algebra', 'Geometry', 'Trigonometry', 'Statistics', 'Probability', 'Calculus', 'Number Bases', 'Sets', 'Logarithms', 'Fractions', 'Decimals', 'Ratios', 'Percentages', 'Indices', 'Surds', 'Grammar', 'Comprehension', 'Vocabulary', 'Oral English', 'Writing', 'Mechanics', 'Thermal Physics', 'Waves', 'Electricity', 'Magnetism', 'Atomic Physics', 'Optics', 'Atomic Structure', 'Chemical Bonding', 'Stoichiometry', 'States of Matter', 'Periodic Table', 'Organic Chemistry', 'Electrochemistry', 'Cell Biology', 'Genetics', 'Ecology', 'Physiology', 'Evolution', 'Classification', 'General', 'Other', name='topic'), postgresql_using=f'{col}::topic',
               existing_nullable=True)
        batch_op.alter_column('difficulty_filter', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('easy', 'medium', 'hard', name='difficultylevel'), postgresql_using='difficulty_filter::difficultylevel',
               existing_nullable=True)
        batch_op.alter_column('assignment_type', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('quiz', 'manual', 'essay', 'practice', name='assignmenttype'), postgresql_using='assignment_type::assignmenttype',
               nullable=True)
        batch_op.alter_column('status', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('draft', 'published', 'archived', 'completed', name='assignmentstatus'), postgresql_using='status::assignmentstatus',
               nullable=True)
        
    # Re-set defaults for PostgreSQL
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("ALTER TABLE assignments ALTER COLUMN assignment_type SET DEFAULT 'quiz'::assignmenttype;")
        op.execute("ALTER TABLE assignments ALTER COLUMN status SET DEFAULT 'draft'::assignmentstatus;")

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('max_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'100'"))
        batch_op.alter_column('is_ai_generated',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('topic')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('subject')

    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.alter_column('selected_option',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('classroom_posts', schema=None) as batch_op:
        batch_op.alter_column('post_type', existing_type=sa.VARCHAR(length=30), type_=sa.Enum('announcement', 'discussion', 'assignment_alert', 'comment', 'resource', name='posttype'), postgresql_using='post_type::posttype',
               existing_nullable=True)

    with op.batch_alter_table('classroom_students', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('subject', existing_type=sa.VARCHAR(length=100), type_=sa.Enum('Mathematics', 'English Language', 'Physics', 'Chemistry', 'Biology', 'Economics', 'Geography', 'Government', 'Civic Education', 'Financial Accounting', 'Agricultural Science', 'Commerce', 'Literature in English', 'Data Science', name='subject'), postgresql_using='subject::subject',
               existing_nullable=True)
        batch_op.alter_column('grade_level', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3', 'Grade 10', 'Grade 11', 'Grade 12', 'University', 'Other', name='gradelevel'), postgresql_using='grade_level::gradelevel',
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'true'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('flashcard_decks', schema=None) as batch_op:
        batch_op.alter_column('subject', existing_type=sa.VARCHAR(length=100), type_=sa.Enum('Mathematics', 'English Language', 'Physics', 'Chemistry', 'Biology', 'Economics', 'Geography', 'Government', 'Civic Education', 'Financial Accounting', 'Agricultural Science', 'Commerce', 'Literature in English', 'Data Science', name='subject'), postgresql_using='subject::subject',
               existing_nullable=False)
        batch_op.alter_column('difficulty', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('easy', 'medium', 'hard', name='difficultylevel'), postgresql_using='difficulty::difficultylevel',
               existing_nullable=False)

    with op.batch_alter_table('question_reports', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('pending', 'reviewed', 'fixed', 'dismissed', name='reportstatus'), postgresql_using='status::reportstatus',
               existing_nullable=True)
        batch_op.alter_column('reason', existing_type=sa.VARCHAR(length=50), type_=sa.Enum('Wrong Answer', 'Typo', 'Unclear Question', 'Missing Diagram', 'Outdated Content', 'Other', name='reportreason'), postgresql_using='reason::reportreason',
               existing_nullable=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('subject', existing_type=sa.VARCHAR(length=100), type_=sa.Enum('Mathematics', 'English Language', 'Physics', 'Chemistry', 'Biology', 'Economics', 'Geography', 'Government', 'Civic Education', 'Financial Accounting', 'Agricultural Science', 'Commerce', 'Literature in English', 'Data Science', name='subject'), postgresql_using='subject::subject',
               existing_nullable=False)
        batch_op.alter_column('topic', existing_type=sa.VARCHAR(length=100), type_=sa.Enum('Algebra', 'Geometry', 'Trigonometry', 'Statistics', 'Probability', 'Calculus', 'Number Bases', 'Sets', 'Logarithms', 'Fractions', 'Decimals', 'Ratios', 'Percentages', 'Indices', 'Surds', 'Grammar', 'Comprehension', 'Vocabulary', 'Oral English', 'Writing', 'Mechanics', 'Thermal Physics', 'Waves', 'Electricity', 'Magnetism', 'Atomic Physics', 'Optics', 'Atomic Structure', 'Chemical Bonding', 'Stoichiometry', 'States of Matter', 'Periodic Table', 'Organic Chemistry', 'Electrochemistry', 'Cell Biology', 'Genetics', 'Ecology', 'Physiology', 'Evolution', 'Classification', 'General', 'Other', name='topic'), postgresql_using=f'{col}::topic',
               nullable=False)
        batch_op.alter_column('difficulty', existing_type=sa.VARCHAR(length=20), type_=sa.Enum('easy', 'medium', 'hard', name='difficultylevel'), postgresql_using='difficulty::difficultylevel',
               existing_nullable=True)
        
        # Check if 'text' column exists before dropping it
        from alembic import context
        inspector = sa.inspect(op.get_bind())
        existing_cols = [c['name'] for c in inspector.get_columns('questions')]
        if 'text' in existing_cols:
            batch_op.drop_column('text')

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.alter_column('contact_frequency',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        
        # Check existing constraints before dropping
        from alembic import context
        inspector = sa.inspect(op.get_bind())
        existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('student_profiles')]
        existing_uniques = [uq['name'] for uq in inspector.get_unique_constraints('student_profiles')]
        
        if 'uq_classroom_student' in existing_uniques:
            batch_op.drop_constraint(batch_op.f('uq_classroom_student'), type_='unique')
        if 'fk_student_profiles_student_id_users' in existing_fks:
            batch_op.drop_constraint(batch_op.f('fk_student_profiles_student_id_users'), type_='foreignkey')
        if 'fk_student_profiles_teacher_id_users' in existing_fks:
            batch_op.drop_constraint(batch_op.f('fk_student_profiles_teacher_id_users'), type_='foreignkey')
        if 'fk_student_profiles_classroom_id_classrooms' in existing_fks:
            batch_op.drop_constraint(batch_op.f('fk_student_profiles_classroom_id_classrooms'), type_='foreignkey')
        
        batch_op.create_foreign_key(batch_op.f('fk_student_profiles_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_student_profiles_student_id_users'), 'users', ['student_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_student_profiles_teacher_id_users'), 'users', ['teacher_id'], ['id'])

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('is_graded',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('teacher_messages', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('sent_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        
        # Check existing constraints before dropping
        from alembic import context
        inspector = sa.inspect(op.get_bind())
        existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('teacher_messages')]
        
        if 'fk_teacher_messages_student_id_users' in existing_fks:
            batch_op.drop_constraint(batch_op.f('fk_teacher_messages_student_id_users'), type_='foreignkey')
        if 'fk_teacher_messages_classroom_id_classrooms' in existing_fks:
            batch_op.drop_constraint(batch_op.f('fk_teacher_messages_classroom_id_classrooms'), type_='foreignkey')
        if 'fk_teacher_messages_teacher_id_users' in existing_fks:
            batch_op.drop_constraint(batch_op.f('fk_teacher_messages_teacher_id_users'), type_='foreignkey')
        
        batch_op.create_foreign_key(batch_op.f('fk_teacher_messages_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_teacher_messages_student_id_users'), 'users', ['student_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_teacher_messages_teacher_id_users'), 'users', ['teacher_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('has_app_installed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
        batch_op.alter_column('study_streak',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        
        # Check existing constraints before dropping
        from alembic import context
        inspector = sa.inspect(op.get_bind())
        existing_uniques = [uq['name'] for uq in inspector.get_unique_constraints('users')]
        
        if 'uq_users_email' in existing_uniques:
            batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        
        batch_op.drop_column('is_superuser')

    # Drop old types after successful migration
    if op.get_bind().dialect.name == 'postgresql':
        for type_name in ['subject', 'topic', 'difficultylevel', 'gradelevel', 'assignmenttype', 'assignmentstatus', 'posttype', 'reportstatus', 'reportreason']:
            op.execute(f"DO $$ BEGIN DROP TYPE IF EXISTS {type_name}_old; EXCEPTION WHEN others THEN null; END $$;")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superuser', sa.BOOLEAN(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.alter_column('study_streak',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('has_app_installed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('teacher_messages', schema=None) as batch_op:
        # Check existing constraints before dropping
        from alembic import context
        inspector = sa.inspect(op.get_bind())
        existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('teacher_messages')]
        
        if 'fk_teacher_messages_teacher_id_users' in existing_fks:
            batch_op.drop_constraint(batch_op.f('fk_teacher_messages_teacher_id_users'), type_='foreignkey')
        if 'fk_teacher_messages_student_id_users' in existing_fks:
            batch_op.drop_constraint(batch_op.f('fk_teacher_messages_student_id_users'), type_='foreignkey')
        if 'fk_teacher_messages_classroom_id_classrooms' in existing_fks:
            batch_op.drop_constraint(batch_op.f('fk_teacher_messages_classroom_id_classrooms'), type_='foreignkey')
        
        batch_op.create_foreign_key(batch_op.f('fk_teacher_messages_teacher_id_users'), 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_teacher_messages_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_teacher_messages_student_id_users'), 'users', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('sent_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_read',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('is_graded',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        # Check existing constraints before dropping
        from alembic import context
        inspector = sa.inspect(op.get_bind())
        existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('student_profiles')]
        
        if 'fk_student_profiles_teacher_id_users' in existing_fks:
            batch_op.drop_constraint(batch_op.f('fk_student_profiles_teacher_id_users'), type_='foreignkey')
        if 'fk_student_profiles_student_id_users' in existing_fks:
            batch_op.drop_constraint(batch_op.f('fk_student_profiles_student_id_users'), type_='foreignkey')
        if 'fk_student_profiles_classroom_id_classrooms' in existing_fks:
            batch_op.drop_constraint(batch_op.f('fk_student_profiles_classroom_id_classrooms'), type_='foreignkey')
        
        batch_op.create_foreign_key(batch_op.f('fk_student_profiles_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_student_profiles_teacher_id_users'), 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_student_profiles_student_id_users'), 'users', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('uq_classroom_student'), ['classroom_id', 'student_id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('contact_frequency',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=False))
        batch_op.alter_column('difficulty',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('topic',
               existing_type=sa.Enum('ALGEBRA', 'GEOMETRY', 'TRIGONOMETRY', 'STATISTICS', 'PROBABILITY', 'CALCULUS', 'NUMBER_BASES', 'SETS', 'LOGARITHMS', 'GRAMMAR', 'COMPREHENSION', 'VOCABULARY', 'ORAL_ENGLISH', 'WRITING', 'MECHANICS', 'THERMAL_PHYSICS', 'WAVES', 'ELECTRICITY', 'MAGNETISM', 'ATOMIC_PHYSICS', 'OPTICS', 'ATOMIC_STRUCTURE', 'CHEMICAL_BONDING', 'STOICHIOMETRY', 'STATES_OF_MATTER', 'PERIODIC_TABLE', 'ORGANIC_CHEMISTRY', 'ELECTROCHEMISTRY', 'CELL_BIOLOGY', 'GENETICS', 'ECOLOGY', 'PHYSIOLOGY', 'EVOLUTION', 'CLASSIFICATION', 'GENERAL', 'OTHER', name='topic'),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', 'AGRICULTURAL_SCIENCE', 'COMMERCE', 'LITERATURE_IN_ENGLISH', name='subject'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('question_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'REVIEWED', 'FIXED', 'DISMISSED', name='reportstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('flashcard_decks', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', 'AGRICULTURAL_SCIENCE', 'COMMERCE', 'LITERATURE_IN_ENGLISH', name='subject'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'true'"))
        batch_op.alter_column('grade_level',
               existing_type=sa.Enum('JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3', 'UNIVERSITY', 'OTHER', name='gradelevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', 'AGRICULTURAL_SCIENCE', 'COMMERCE', 'LITERATURE_IN_ENGLISH', name='subject'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('classroom_students', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('classroom_posts', schema=None) as batch_op:
        batch_op.alter_column('post_type',
               existing_type=sa.Enum('ANNOUNCEMENT', 'DISCUSSION', 'ASSIGNMENT_ALERT', 'COMMENT', 'RESOURCE', name='posttype'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.alter_column('selected_option',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', 'COMPLETED', name='assignmentstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'"))
        batch_op.alter_column('is_ai_generated',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('max_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'100'"))
        batch_op.alter_column('assignment_type',
               existing_type=sa.Enum('QUIZ', 'MANUAL', 'ESSAY', 'PRACTICE', name='assignmenttype'),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'quiz'"))
        batch_op.alter_column('difficulty_filter',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('topic_filter',
               existing_type=sa.Enum('ALGEBRA', 'GEOMETRY', 'TRIGONOMETRY', 'STATISTICS', 'PROBABILITY', 'CALCULUS', 'NUMBER_BASES', 'SETS', 'LOGARITHMS', 'GRAMMAR', 'COMPREHENSION', 'VOCABULARY', 'ORAL_ENGLISH', 'WRITING', 'MECHANICS', 'THERMAL_PHYSICS', 'WAVES', 'ELECTRICITY', 'MAGNETISM', 'ATOMIC_PHYSICS', 'OPTICS', 'ATOMIC_STRUCTURE', 'CHEMICAL_BONDING', 'STOICHIOMETRY', 'STATES_OF_MATTER', 'PERIODIC_TABLE', 'ORGANIC_CHEMISTRY', 'ELECTROCHEMISTRY', 'CELL_BIOLOGY', 'GENETICS', 'ECOLOGY', 'PHYSIOLOGY', 'EVOLUTION', 'CLASSIFICATION', 'GENERAL', 'OTHER', name='topic'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('subject_filter',
               existing_type=sa.Enum('MATHEMATICS', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'ECONOMICS', 'GEOGRAPHY', 'GOVERNMENT', 'CIVIC_EDUCATION', 'FINANCIAL_ACCOUNTING', 'AGRICULTURAL_SCIENCE', 'COMMERCE', 'LITERATURE_IN_ENGLISH', name='subject'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # Drop Enum types in PostgreSQL
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DROP TYPE IF EXISTS subject;")
        op.execute("DROP TYPE IF EXISTS topic;")
        op.execute("DROP TYPE IF EXISTS difficultylevel;")
        op.execute("DROP TYPE IF EXISTS assignmenttype;")
        op.execute("DROP TYPE IF EXISTS assignmentstatus;")
        op.execute("DROP TYPE IF EXISTS posttype;")
        op.execute("DROP TYPE IF EXISTS reportstatus;")
        op.execute("DROP TYPE IF EXISTS gradelevel;")

    # ### end Alembic commands ###
