"""add_new_enum_types_and_update_models

Revision ID: f9c39d9b31f2
Revises: d0d79fcca71f
Create Date: 2025-12-18 16:29:26.174234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c39d9b31f2'
down_revision: Union[str, None] = 'd0d79fcca71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new Enum types for PostgreSQL
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DO $$ BEGIN CREATE TYPE assettype AS ENUM ('image', 'pdf', 'video', 'audio', 'document', 'other'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
        op.execute("DO $$ BEGIN CREATE TYPE otptype AS ENUM ('password_reset', 'phone_verify', 'email_verify', 'login'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
        op.execute("DO $$ BEGIN CREATE TYPE userrole AS ENUM ('student', 'teacher', 'admin', 'moderator'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

        # Convert columns to VARCHAR temporarily
        op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(50)")
        op.execute("ALTER TABLE users ALTER COLUMN education_level TYPE VARCHAR(50)")
        op.execute("ALTER TABLE otps ALTER COLUMN purpose TYPE VARCHAR(20)")
        op.execute("ALTER TABLE assets ALTER COLUMN asset_type TYPE VARCHAR(50)")

        # Normalize data before casting
        op.execute("UPDATE users SET role = LOWER(role::text) WHERE role IS NOT NULL")
        op.execute("UPDATE otps SET purpose = LOWER(purpose::text) WHERE purpose IS NOT NULL")
        op.execute("UPDATE assets SET asset_type = LOWER(asset_type::text) WHERE asset_type IS NOT NULL")
        op.execute("""
            UPDATE users SET education_level = CASE 
                WHEN UPPER(education_level::text) IN ('JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3') THEN UPPER(education_level::text)
                WHEN education_level::text ILIKE 'grade%10%' THEN 'Grade 10'
                WHEN education_level::text ILIKE 'grade%11%' THEN 'Grade 11'
                WHEN education_level::text ILIKE 'grade%12%' THEN 'Grade 12'
                WHEN UPPER(education_level::text) = 'UNIVERSITY' THEN 'University'
                ELSE INITCAP(education_level::text)
            END WHERE education_level IS NOT NULL
        """)

        # Drop defaults that cause casting issues in PostgreSQL
        op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT;")

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('asset_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('image', 'pdf', 'video', 'audio', 'document', 'other', name='assettype'),
               postgresql_using='asset_type::assettype' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=False)

    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.alter_column('purpose',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('password_reset', 'phone_verify', 'email_verify', 'login', name='otptype'),
               postgresql_using='purpose::otptype' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('student', 'teacher', 'admin', 'moderator', name='userrole'),
               postgresql_using='role::userrole' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=True)
        batch_op.alter_column('education_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3', 'Grade 10', 'Grade 11', 'Grade 12', 'University', 'Other', name='gradelevel'),
               postgresql_using='education_level::gradelevel' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=True)

    # Re-set defaults for PostgreSQL
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'student'::userrole;")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT;")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('education_level',
               existing_type=sa.Enum('JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3', 'University', 'Other', name='gradelevel'),
               type_=sa.VARCHAR(length=50),
               postgresql_using='education_level::varchar' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.Enum('student', 'teacher', 'admin', 'moderator', name='userrole'),
               type_=sa.VARCHAR(length=50),
               postgresql_using='role::varchar' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=True)

    if op.get_bind().dialect.name == 'postgresql':
        op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'student';")

    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.alter_column('purpose',
               existing_type=sa.Enum('password_reset', 'phone_verify', 'email_verify', 'login', name='otptype'),
               type_=sa.VARCHAR(length=20),
               postgresql_using='purpose::varchar' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('asset_type',
               existing_type=sa.Enum('image', 'pdf', 'video', 'audio', 'document', 'other', name='assettype'),
               type_=sa.VARCHAR(length=50),
               postgresql_using='asset_type::varchar' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=False)

    # Drop Enum types in PostgreSQL
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DROP TYPE IF EXISTS assettype;")
        op.execute("DROP TYPE IF EXISTS otptype;")
        op.execute("DROP TYPE IF EXISTS userrole;")
    # ### end Alembic commands ###
