"""add_new_enum_types_and_update_models

Revision ID: f9c39d9b31f2
Revises: d0d79fcca71f
Create Date: 2025-12-18 16:29:26.174234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c39d9b31f2'
down_revision: Union[str, None] = 'd0d79fcca71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new Enum types for PostgreSQL
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DO $$ BEGIN CREATE TYPE assettype AS ENUM ('IMAGE', 'PDF', 'VIDEO', 'AUDIO', 'DOCUMENT', 'OTHER'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
        op.execute("DO $$ BEGIN CREATE TYPE otptype AS ENUM ('PASSWORD_RESET', 'PHONE_VERIFY', 'EMAIL_VERIFY', 'LOGIN'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
        op.execute("DO $$ BEGIN CREATE TYPE userrole AS ENUM ('STUDENT', 'TEACHER', 'ADMIN', 'MODERATOR'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('asset_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('IMAGE', 'PDF', 'VIDEO', 'AUDIO', 'DOCUMENT', 'OTHER', name='assettype'),
               postgresql_using='asset_type::assettype' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=False)

    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.alter_column('purpose',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PASSWORD_RESET', 'PHONE_VERIFY', 'EMAIL_VERIFY', 'LOGIN', name='otptype'),
               postgresql_using='purpose::otptype' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('STUDENT', 'TEACHER', 'ADMIN', 'MODERATOR', name='userrole'),
               postgresql_using='role::userrole' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=True,
               existing_server_default=sa.text("'student'"))
        batch_op.alter_column('education_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3', 'UNIVERSITY', 'OTHER', name='gradelevel'),
               postgresql_using='education_level::gradelevel' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('education_level',
               existing_type=sa.Enum('JSS1', 'JSS2', 'JSS3', 'SS1', 'SS2', 'SS3', 'UNIVERSITY', 'OTHER', name='gradelevel'),
               type_=sa.VARCHAR(length=50),
               postgresql_using='education_level::varchar' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.Enum('STUDENT', 'TEACHER', 'ADMIN', 'MODERATOR', name='userrole'),
               type_=sa.VARCHAR(length=50),
               postgresql_using='role::varchar' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=True,
               existing_server_default=sa.text("'student'"))

    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.alter_column('purpose',
               existing_type=sa.Enum('PASSWORD_RESET', 'PHONE_VERIFY', 'EMAIL_VERIFY', 'LOGIN', name='otptype'),
               type_=sa.VARCHAR(length=20),
               postgresql_using='purpose::varchar' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('asset_type',
               existing_type=sa.Enum('IMAGE', 'PDF', 'VIDEO', 'AUDIO', 'DOCUMENT', 'OTHER', name='assettype'),
               type_=sa.VARCHAR(length=50),
               postgresql_using='asset_type::varchar' if op.get_bind().dialect.name == 'postgresql' else None,
               existing_nullable=False)

    # Drop Enum types in PostgreSQL
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DROP TYPE IF EXISTS assettype;")
        op.execute("DROP TYPE IF EXISTS otptype;")
        op.execute("DROP TYPE IF EXISTS userrole;")
    # ### end Alembic commands ###
