"""Centralized Enums for the Base10 platform to ensure strict data integrity."""
import enum

class Subject(str, enum.Enum):
    """WAEC subjects."""
    MATHEMATICS = "Mathematics"
    ENGLISH = "English Language"
    PHYSICS = "Physics"
    CHEMISTRY = "Chemistry"
    BIOLOGY = "Biology"
    ECONOMICS = "Economics"
    GEOGRAPHY = "Geography"
    GOVERNMENT = "Government"
    CIVIC_EDUCATION = "Civic Education"
    FINANCIAL_ACCOUNTING = "Financial Accounting"
    AGRICULTURAL_SCIENCE = "Agricultural Science"
    COMMERCE = "Commerce"
    LITERATURE_IN_ENGLISH = "Literature in English"

class UserRole(str, enum.Enum):
    """Platform user roles."""
    STUDENT = "student"
    TEACHER = "teacher"
    ADMIN = "admin"
    MODERATOR = "moderator"

class AssetType(str, enum.Enum):
    """Types of media assets."""
    IMAGE = "image"
    PDF = "pdf"
    VIDEO = "video"
    AUDIO = "audio"
    DOCUMENT = "document"
    OTHER = "other"

class OTPType(str, enum.Enum):
    """Purpose of an OTP."""
    PASSWORD_RESET = "password_reset"
    PHONE_VERIFY = "phone_verify"
    EMAIL_VERIFY = "email_verify"
    LOGIN = "login"

class QuestionType(str, enum.Enum):
    """Types of questions."""
    MULTIPLE_CHOICE = "multiple_choice"
    TRUE_FALSE = "true_false"
    SHORT_ANSWER = "short_answer"
    ESSAY = "essay"

class NotificationType(str, enum.Enum):
    """Types of notifications."""
    SMS = "sms"
    EMAIL = "email"
    PUSH = "push"
    IN_APP = "in_app"

class DifficultyLevel(str, enum.Enum):
    """Question difficulty levels."""
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"

class GradeLevel(str, enum.Enum):
    """Educational grade levels."""
    JSS1 = "JSS1"
    JSS2 = "JSS2"
    JSS3 = "JSS3"
    SS1 = "SS1"
    SS2 = "SS2"
    SS3 = "SS3"
    UNIVERSITY = "University"
    OTHER = "Other"

class AssignmentType(str, enum.Enum):
    """Types of assignments."""
    QUIZ = "quiz"
    MANUAL = "manual"
    ESSAY = "essay"
    PRACTICE = "practice"

class AssignmentStatus(str, enum.Enum):
    """Status of an assignment."""
    DRAFT = "draft"
    PUBLISHED = "published"
    ARCHIVED = "archived"
    COMPLETED = "completed"

class PostType(str, enum.Enum):
    """Types of classroom stream posts."""
    ANNOUNCEMENT = "announcement"
    DISCUSSION = "discussion"
    ASSIGNMENT_ALERT = "assignment_alert"
    COMMENT = "comment"
    RESOURCE = "resource"

class ReportStatus(str, enum.Enum):
    """Status of a content report."""
    PENDING = "pending"
    REVIEWED = "reviewed"
    FIXED = "fixed"
    DISMISSED = "dismissed"

class ReportReason(str, enum.Enum):
    """Predefined report reasons for consistency."""
    WRONG_ANSWER = "Wrong Answer"
    TYPO = "Typo"
    UNCLEAR_QUESTION = "Unclear Question"
    MISSING_DIAGRAM = "Missing Diagram"
    OUTDATED_CONTENT = "Outdated Content"
    OTHER = "Other"

class Topic(str, enum.Enum):
    """
    Comprehensive list of WAEC topics.
    This ensures strict input and accurate dropdowns in the UI.
    """
    # Mathematics
    ALGEBRA = "Algebra"
    ALGEBRAIC_EQUATIONS = "Algebraic Equations"
    ALGEBRAIC_EVALUATION = "Algebraic Evaluation"
    ALGEBRAIC_FRACTIONS = "Algebraic Fractions"
    ALGEBRAIC_SIMPLIFICATION = "Algebraic Simplification"
    APPROXIMATION = "Approximation"
    BEARINGS = "Bearings"
    CALCULUS = "Calculus"
    CHANGE_OF_SUBJECT = "Change of Subject"
    CIRCLE_GEOMETRY = "Circle Geometry"
    COORDINATE_GEOMETRY = "Coordinate Geometry"
    FACTORIZATION = "Factorization"
    FRACTIONS = "Fractions"
    FUNCTIONS = "Functions"
    GEOMETRY = "Geometry"
    GRAPHS = "Graphs"
    INEQUALITIES = "Inequalities"
    LOGARITHMS = "Logarithms"
    MEASUREMENT = "Measurement"
    MENSURATION = "Mensuration"
    MODULAR_ARITHMETIC = "Modular Arithmetic"
    NUMBER_BASES = "Number Bases"
    POLYGONS = "Polygons"
    PROBABILITY = "Probability"
    QUADRATIC_EQUATIONS = "Quadratic Equations"
    RATES = "Rates"
    RATIOS = "Ratios"
    SEQUENCES = "Sequences"
    SETS = "Sets"
    STATISTICS = "Statistics"
    SURDS = "Surds"
    TRIGONOMETRY = "Trigonometry"
    VECTORS = "Vectors"
    WORD_PROBLEMS = "Word Problems"
    
    # English
    COMPREHENSION = "Comprehension"
    GRAMMAR = "Grammar"
    ORAL_ENGLISH = "Oral English"
    VOCABULARY = "Vocabulary"
    WRITING = "Writing"
    
    # Physics
    ALTERNATING_CURRENT = "Alternating Current"
    ATOMIC_PHYSICS = "Atomic Physics"
    CAPACITORS = "Capacitors"
    CAPILLARITY = "Capillarity"
    CURRENT_ELECTRICITY = "Current Electricity"
    DENSITY = "Density"
    DOMESTIC_ELECTRICITY = "Domestic Electricity"
    DYNAMICS = "Dynamics"
    EARTH_ROTATION_AND_REVOLUTION = "Earth Rotation and Revolution"
    EARTH_STRUCTURE = "Earth Structure"
    ELASTIC_PROPERTIES_OF_SOLIDS = "Elastic Properties of Solids"
    ELECTRICITY = "Electricity"
    ELECTROMAGNETIC_INDUCTION = "Electromagnetic Induction"
    ELECTROMAGNETIC_SPECTRUM = "Electromagnetic Spectrum"
    ELECTROMAGNETISM = "Electromagnetism"
    ELECTROSTATIC = "Electrostatics"
    ENERGY_RESOURCES = "Energy Resources"
    EQUILIBRIUM_OF_FORCES = "Equilibrium of Forces"
    GAS_LAWS = "Gas Laws"
    GRAVITATION = "Gravitation"
    HEAT_QUANTITIES = "Heat Quantities"
    HEAT_TRANSFER = "Heat Transfer"
    KINEMATICS = "Kinematics"
    KINETIC_THEORY = "Kinetic Theory"
    LAWS_OF_MOTION = "Laws of Motion"
    LENSES = "Lenses"
    LIGHT = "Light"
    MACHINES = "Machines"
    MAGNETISM = "Magnetism"
    MECHANICS = "Mechanics"
    OPTICAL_INSTRUMENTS = "Optical Instruments"
    OPTICS = "Optics"
    PRESSURE = "Pressure"
    PROJECTILES = "Projectiles"
    QUANTUM_PHYSICS = "Quantum Physics"
    RADIOACTIVITY = "Radioactivity"
    REFRACTION = "Refraction"
    SIMPLE_HARMONIC_MOTION = "Simple Harmonic Motion"
    SOUND = "Sound"
    TEMPERATURE = "Temperature"
    THERMAL_EXPANSION = "Thermal Expansion"
    THERMAL_PHYSICS = "Thermal Physics"
    THE_SOLAR_SYSTEM = "The Solar System"
    WAVES = "Waves"
    WORK_ENERGY_AND_POWER = "Work, Energy and Power"
    
    # Chemistry
    ATOMIC_STRUCTURE = "Atomic Structure"
    CHEMICAL_BONDING = "Chemical Bonding"
    ELECTROCHEMISTRY = "Electrochemistry"
    ORGANIC_CHEMISTRY = "Organic Chemistry"
    PERIODIC_TABLE = "Periodic Table"
    STATES_OF_MATTER = "States of Matter"
    STOICHIOMETRY = "Stoichiometry"
    
    # Biology
    ADAPTATION = "Adaptation"
    BIOENERGETICS = "Bioenergetics"
    CELL_BIOLOGY = "Cell Biology"
    CELL_STRUCTURE = "Cell Structure"
    CIRCULATORY_SYSTEM = "Circulatory System"
    CLASSIFICATION_OF_LIVING_THINGS = "Classification of Living Things"
    CONSERVATION = "Conservation"
    ECOLOGY = "Ecology"
    EVOLUTION = "Evolution"
    GENETICS = "Genetics"
    HEALTH = "Health"
    HEALTH_ISSUES = "Health Issues"
    HIV_AIDS = "HIV/AIDS"
    HORMONAL_COORDINATION = "Hormonal Coordination"
    HORMONAL_COORDINATION_IN_PLANTS = "Hormonal Coordination in Plants"
    MICROBIOLOGY = "Microbiology"
    NERVOUS_SYSTEM = "Nervous System"
    NUTRITION = "Nutrition"
    ORGANIZATION_OF_LIFE = "Organization of Life"
    PHOTOSYNTHESIS = "Photosynthesis"
    PHYSIOLOGY = "Physiology"
    PLANT_CLASSIFICATION = "Plant Classification"
    PLANT_NUTRITION = "Plant Nutrition"
    PROTISTS = "Protists"
    REPRODUCTION = "Reproduction"
    REPRODUCTION_IN_PLANTS = "Reproduction in Plants"
    RESPIRATION = "Respiration"
    RESPONSE_IN_PLANTS = "Response in Plants"
    SOCIAL_INSECTS = "Social Insects"
    TISSUES_AND_CELLS = "Tissues and Cells"
    TRANSPORT_IN_PLANTS = "Transport in Plants"
    TRANSPORT_SYSTEMS = "Transport Systems"
    VARIATION = "Variation"
    
    # Government
    ARMS_OF_GOVERNMENT = "Arms of Government"
    BASIC_CONCEPTS_OF_GOVERNMENT = "Basic Concepts of Government"
    CABINET_SYSTEM = "Cabinet System"
    CHECKS_AND_BALANCES = "Checks and Balances"
    CITIZENSHIP = "Citizenship"
    CITIZENSHIP_DUTIES = "Citizenship Duties"
    CIVIL_SOCIETY = "Civil Society"
    COLONIAL_ADMINISTRATION = "Colonial Administration"
    COLONIALISM = "Colonialism"
    CONSTITUTIONAL_DEVELOPMENT = "Constitutional Development"
    CONSTITUTIONS = "Constitutions"
    CULTISM = "Cultism"
    DEMOCRACY = "Democracy"
    ELECTIONS = "Elections"
    ELECTORAL_COMMISSION = "Electoral Commission"
    ELECTORAL_SYSTEMS = "Electoral Systems"
    EMPOWERMENT = "Empowerment"
    EXAMINATION_MALPRACTICE = "Examination Malpractice"
    FEDERALISM = "Federalism"
    FOREIGN_POLICY = "Foreign Policy"
    FRENCH_COLONIAL_ADMINISTRATION = "French Colonial Administration"
    FUNCTIONS_OF_GOVERNMENT = "Functions of Government"
    GOVERNMENT_AGENCIES = "Government Agencies"
    HUMAN_RIGHTS = "Human Rights"
    HUMAN_TRAFFICKING = "Human Trafficking"
    INTER_COMMUNAL_RELATIONSHIPS = "Inter-communal Relationships"
    INTERPERSONAL_RELATIONSHIPS = "Interpersonal Relationships"
    INTERNATIONAL_ORGANIZATIONS = "International Organizations"
    JUDICIARY = "Judiciary"
    JUSTICE = "Justice"
    LAW_AND_ORDER = "Law and Order"
    LEGISLATURE = "Legislature"
    LEGITIMACY = "Legitimacy"
    LOCAL_GOVERNMENT = "Local Government"
    MILITARY_RULE = "Military Rule"
    MONARCHY = "Monarchy"
    NATIONAL_CONSCIOUSNESS = "National Consciousness"
    NATIONALISM = "Nationalism"
    ORDERLINESS = "Orderliness"
    PARTY_SYSTEMS = "Party Systems"
    POLITICAL_APATHY = "Political Apathy"
    POLITICAL_IDEOLOGIES = "Political Ideologies"
    POLITICAL_PARTIES = "Political Parties"
    POLITICAL_SOCIALIZATION = "Political Socialization"
    POWER_AND_AUTHORITY = "Power and Authority"
    PRE_COLONIAL_ADMINISTRATION = "Pre-Colonial Administration"
    PRESIDENTIAL_SYSTEM = "Presidential System"
    PRESSURE_GROUPS = "Pressure Groups"
    PUBLIC_ADMINISTRATION = "Public Administration"
    PUBLIC_CORPORATIONS = "Public Corporations"
    PUBLIC_OPINION = "Public Opinion"
    PUBLIC_SERVICE = "Public Service"
    REPRESENTATIVE_GOVERNMENT = "Representative Government"
    RESPONSIBLE_PARENTHOOD = "Responsible Parenthood"
    RULE_OF_LAW = "Rule of Law"
    SEPARATION_OF_POWERS = "Separation of Powers"
    STUDY_OF_GOVERNMENT = "Study of Government"
    SYSTEMS_OF_GOVERNMENT = "Systems of Government"
    THE_STATE = "The State"
    TRAFFIC_REGULATIONS = "Traffic Regulations"
    TYPES_OF_GOVERNMENT = "Types of Government"
    UNITARY_SYSTEM = "Unitary System"
    VALUES = "Values"
    YOUTH_EMPOWERMENT = "Youth Empowerment"
    
    # Financial Accounting
    ACCOUNTING_CONCEPTS = "Accounting Concepts"
    ACCOUNTING_PROCESS = "Accounting Process"
    ADJUSTMENTS_PROVISIONS = "Adjustments - Provisions"
    ASSETS = "Assets"
    BALANCE_SHEET_CLASSIFICATION = "Balance Sheet Classification"
    BANK_RECONCILIATION = "Bank Reconciliation"
    BOOKS_OF_ORIGINAL_ENTRY = "Books of Original Entry"
    CLASSIFICATION_OF_ACCOUNTS = "Classification of Accounts"
    COMPANY_ACCOUNTS = "Company Accounts"
    COMPANY_CHARACTERISTICS = "Company Characteristics"
    CONTROL_ACCOUNTS = "Control Accounts"
    DEPARTMENTAL_ACCOUNTS = "Departmental Accounts"
    DEPRECIATION = "Depreciation"
    ELECTRONIC_DATA_PROCESSING = "Electronic Data Processing"
    ERRORS = "Errors"
    FINAL_ACCOUNTS = "Final Accounts"
    FINAL_ACCOUNTS_OF_A_SOLE_TRADER = "Final Accounts of a Sole Trader"
    INFORMATION_TECHNOLOGY = "Information Technology"
    INTRODUCTION_TO_ACCOUNTING = "Introduction to Accounting"
    LEDGERS = "Ledgers"
    MANUFACTURING_ACCOUNT = "Manufacturing Account"
    NON_PROFIT_ACCOUNTS = "Non-Profit Accounts"
    PARTNERSHIP_ACCOUNTS = "Partnership Accounts"
    PETTY_CASH = "Petty Cash"
    SINGLE_ENTRY_AND_INCOMPLETE_RECORDS = "Single Entry and Incomplete Records"
    SOURCE_DOCUMENTS = "Source Documents"
    TRADING_ACCOUNT = "Trading Account"
    TRIAL_BALANCE = "Trial Balance"
    WORKING_CAPITAL = "Working Capital"
    
    # Geography
    AGRICULTURE = "Agriculture"
    CLIMATE_ENVIRONMENTAL_LAPSE_RATE = "Climate / Environmental Lapse Rate"
    CLIMATE_RAINFALL = "Climate / Rainfall"
    COASTAL_PROCESSES = "Coastal Processes"
    DESERT_LANDFORMS = "Desert Landforms"
    ECONOMIC_GEOGRAPHY = "Economic Geography"
    ECONOMIC_INTEGRATION_ECOWAS = "Economic Integration / ECOWAS"
    ENVIRONMENTAL_RESOURCES = "Environmental Resources"
    GEOMORPHIC_PROCESSES_EROSION = "Geomorphic Processes / Erosion"
    INDUSTRY = "Industry"
    LIMESTONE_GEOGRAPHY = "Limestone Geography"
    LONGITUDE_AND_TIME = "Longitude and Time"
    MAP_READING = "Map Reading"
    MAP_READING_ECONOMIC_ACTIVITIES = "Map Reading / Economic Activities"
    MAP_READING_PHYSICAL_FEATURES = "Map Reading / Physical Features"
    MIGRATION_SETTLEMENT = "Migration / Settlement"
    PHYSICAL_GEOGRAPHY_LANDFORMS = "Physical Geography / Landforms"
    POPULATION_GEOGRAPHY = "Population Geography"
    POPULATION_GEOGRAPHY_MIGRATION = "Population Geography / Migration"
    RIVER_PROCESSES = "River Processes"
    ROCKS = "Rocks"
    SETTLEMENT_GEOGRAPHY = "Settlement Geography"
    SETTLEMENT_PATTERNS = "Settlement Patterns"
    TRADE = "Trade"
    TRADE_ECONOMICS = "Trade / Economics"
    TRANSPORTATION = "Transportation"
    VOLCANICITY = "Volcanicity"
    WEATHERING = "Weathering"
    WEATHER_INSTRUMENTS = "Weather Instruments"
    WIND_ACTION = "Wind Action"
    
    # Additional topics
    SIMPLE_INTEREST = "Simple Interest"
    DRUG_ABUSE = "Drug Abuse"
    
    # General/Other
    GENERAL = "General"
    OTHER = "Other"
